### ISSUE TITLE
Wait for pods to come up on other nodes before rebooting

### ISSUE THREAD

**Issue by andor44** [coreos/container-linux-update-operator#134]
In low node count, high pod density clusters sending a pod delete request then just rebooting can still be very disruptive, as the now terminating pods need some time to become available on other nodes. Therefore it might be desirable to wait for the pods that were previously running on the rebooting node to become available. I am aware that determining when this occurs is far from trivial, maybe to the point where it's outside the scope of this project, therefore I have a simple suggestion that would already cover quite a few use-cases: a user-configurable grace period to wait with the reboot after the pod kill requests have been sent to the API, eg.

```
 $ update-agent --pod-grace-period 5m
```

Likely related to #50, feel free to close if you feel the overlap between that and this is too large.

**Comment by dghubble** [comment]
CLUO supports before-reboot (and after-reboot) required annotations. This means you can add a custom DaemonSet so that a pod will run on a node when a reboot is eminent. Your pod may perform whatever custom actions you like, including draining pods, polling for services to become available or running elsewhere, or waiting a fixed period. Your custom pod then adds the required annotation to allow the drain and reboot to occur (in your case, perhaps you've already drained the node).

We built this mechanism to allow folks to write customizations like this that are specific to their unique needs.

**Comment by dghubble** [comment]
A subproblem to this is waiting until pods delete before terminating the node. With #137, we'd best-effort wait for pods to terminate, but can't provide a hard guarantee without potentially stalling updates (undesired). Waiting for an additional window of time beyond that should be in the realm of writing a custom before-reboot DaemonSet and not directly a CLUO responsbility imo.

**Comment by andor44** [comment]
Makes sense; thanks @dghubble!
