### ISSUE TITLE
Should play nice with "pod disruption budgets"

### ISSUE THREAD

**Issue by euank** [coreos/container-linux-update-operator#50]
This will make deleting things less fragile.

In the case of non-CVE updates, there's not too much risk in trying to fit within such budgets via draining more slowly.

Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-disruption-budget

**Comment by wking** [comment]
> I'd be happy to steal drain code if it fits.

Instead of copy/pasting this around, it seems like it would be easier to have a centrally-maintained node-draining library.  I've pulled the `kubectl` implementation out into a separate library [here][1], and I'm [trying][2] to get that library landed somewhere under client-go upstream.  If that sounds appealing, help getting the library landed in client-go would be great :).

[1]: https://github.com/wking/kubernetes-drain
[2]: https://github.com/kubernetes/kubernetes/issues/25625#issuecomment-405056988

**Comment by euank** [comment]
Container Linux is deprecated. Closing this issue as stale.
